### ISSUE TITLE
拒绝连接   can not initialize cipher context

### ISSUE THREAD

**Issue by BenThang** [shadowsocksrr/electron-ssr#126]
2022-09-21 19:09:01:282 [info] pac server listen at: 127.0.0.1:2333
2022-09-21 19:09:01:282 [info] http proxy server listen at: 127.0.0.1:12333
2022-09-21 19:09:01:447 [info] IPv6 support

2022-09-21 19:09:01:447 [error] 2022-09-21 19:09:01 INFO     util.py:85 loading libcrypto from libcrypto.so.3
Traceback (most recent call last):
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/rc4_md5.py", line 33, in create_cipher
    return openssl.OpenSSLCrypto(b'rc4', rc4_key, b'', op)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 104, in __init__
    raise Exception('can not initialize cipher context')
Exception: can not initialize cipher context

2022-09-21 19:09:01:451 [info] next subscribe update time: Thu Sep 22 2022 19:09:01 GMT+0800 (CST)

(electron-ssr:13988): libnotify-WARNING **: 19:09:02.029: Failed to connect to proxy

(electron-ssr:13988): libnotify-WARNING **: 19:09:02.030: Failed to connect to proxy

(electron-ssr:13988): libnotify-WARNING **: 19:09:02.031: Failed to connect to proxy
^C
(process:14886): dconf-WARNING **: 19:10:07.512: failed to commit changes to dconf: 无法连接： 拒绝连接
2022-09-21 19:10:07:516 [info] Kill client
2022-09-21 19:10:07:519 [info] http proxy server closed.
2022-09-21 19:10:07:519 [info] pac server closed.
2022-09-21 19:10:07:536 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: kill ESRCH
[1]    13925 segmentation fault  sudo ./electron-ssr

**Comment by heijieke** [comment]
我也遇到同样的问题了，请问这个问题最后解决了没有？

**Comment by cerfly** [comment]
+1, 同遇到类似问题

2022-10-08 21:20:02:136 [info] pac server listen at: 127.0.0.1:2333
2022-10-08 21:20:02:136 [info] http proxy server listen at: 127.0.0.1:12333
2022-10-08 21:20:02:156 [info] next subscribe update time: Sun Oct 09 2022 21:20:02 GMT+0800 (HKT)
2022-10-08 21:20:02:162 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_CONNECTION_REFUSED
2022-10-08 21:20:02:188 [error] 2022-10-08 21:20:02 INFO     util.py:94 loading libcrypto from libcrypto.so.3

2022-10-08 21:20:02:189 [info] IPv6 support

2022-10-08 21:20:02:189 [error] Traceback (most recent call last):
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 303, in get_config
    check_config(config, is_local)
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 132, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 91, in __init__
    random_string(self._method_info[1]))
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 120, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/rc4_md5.py", line 33, in create_cipher
    return openssl.OpenSSLCrypto(b'rc4', rc4_key, b'', op)
  File "/home/cerfly/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 110, in __init__
    raise Exception('can not initialize cipher context')
Exception: can not initialize cipher context

**Comment by Night-Street** [comment]
同,我也遇到了
2022-10-30 19:20:04:191 [info] pac server listen at: 127.0.0.1:2333
2022-10-30 19:20:04:191 [info] http proxy server listen at: 127.0.0.1:12333
2022-10-30 19:20:04:255 [info] IPv6 support

2022-10-30 19:20:04:256 [error] 2022-10-30 19:20:04 INFO     util.py:85 loading libcrypto from libcrypto.so.3
Traceback (most recent call last):
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/rc4_md5.py", line 33, in create_cipher
    return openssl.OpenSSLCrypto(b'rc4', rc4_key, b'', op)
  File "/home/chen/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 104, in __init__
    raise Exception('can not initialize cipher context')
Exception: can not initialize cipher context

**Comment by panqiincs** [comment]
我也遇到了同样的问题。

**Comment by UnknownCUnknown** [comment]
诸君，可以试下这个，对我有效。https://github.com/TyrantLucifer/ssr-command-client/issues/90
主要是这个issue里提到的https://blog.vinsonws.cn/2023/05/25/openssl-openssl3-%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF-rc4-md5-%E6%94%AF%E6%8C%81/
希望对诸君有用！

**Comment by yww325** [comment]
> 诸君，可以试下这个，对我有效。[TyrantLucifer/ssr-command-client#90](https://github.com/TyrantLucifer/ssr-command-client/issues/90) 主要是这个issue里提到的https://blog.vinsonws.cn/2023/05/25/openssl-openssl3-%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF-rc4-md5-%E6%94%AF%E6%8C%81/ 希望对诸君有用！

厉害了！问题解决了。
