### ISSUE TITLE
Ubuntu22.04无法正常使用electron-ssr-0.2.7

### ISSUE THREAD

**Issue by lss-len** [shadowsocksrr/electron-ssr#127]
2022-11-02 15:44:52:700 [info] last update time: Wed Nov 02 2022 15:44:52 GMT+0800 (CST)
2022-11-02 15:44:52:728 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2022-11-02 15:44:52:731 [info] run command: python /home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s hkt2.yubb12.site -p 11393 -k ****** -m aes-256-cfb -O auth_aes128_sha1 -G 172887:bWWjzA -o http_simple -g 30712172887.microsoft.com -b 127.0.0.1 -l 1080
2022-11-02 15:44:52:734 [info] pac server listen at: 127.0.0.1:2333
2022-11-02 15:44:52:735 [info] http proxy server listen at: 127.0.0.1:12333
2022-11-02 15:44:52:739 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_CONNECTION_REFUSED
2022-11-02 15:44:52:751 [info] next subscribe update time: Thu Nov 03 2022 15:44:52 GMT+0800 (CST)
2022-11-02 15:44:52:780 [info] IPv6 support

2022-11-02 15:44:52:879 [error] Traceback (most recent call last):
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 89, in __init__
    self.cipher = self.get_cipher(key, method, 1,
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 89, in __init__
    load_openssl()
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 37, in load_openssl
    libcrypto = util.find_library(('crypto', 'eay32'),
  File "/home/lss/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/util.py", line 60, in find_library
    path = ctypes.util.find_library(name)
  File "/usr/lib/python3.10/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.10/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.10/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibcrypto.a'

2022-11-02 15:44:53:909 [error] Unhandled Rejection at: Promise [object Promise], reason: SentryError: HTTP Error (429)

**Comment by feeliam** [comment]
同遇到这个问题，怎么解决？

**Comment by Eku127** [comment]
https://cloud.tencent.com/developer/article/2524397 Try this.
