### ISSUE TITLE
Centos 7 添加完订阅地址后报错 --- libsodium not found

### ISSUE THREAD

**Issue by iefhong** [shadowsocksrr/electron-ssr#51]
[root@centos-master temp]# electron-ssr 

(process:14764): dconf-WARNING **: 15:46:24.694: failed to commit changes to dconf: 连接已关闭

(process:14780): dconf-WARNING **: 15:46:24.741: failed to commit changes to dconf: 连接已关闭
2020-02-13 15:46:24:767 [info] Register shortcut: toggleWindow, Ctrl+Shift+W
2020-02-13 15:46:24:822 [info] run command: python /root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s [订阅地址] -p 35212 -k ****** -m chacha20-ietf -O origin -o plain -b 127.0.0.1 -l 1080
2020-02-13 15:46:24:866 [info] pac server listen at: 127.0.0.1:2333
2020-02-13 15:46:24:866 [info] http proxy server listen at: 127.0.0.1:12333

(electron-ssr:14692): libappindicator-WARNING **: 15:46:24.936: Unable to get the session bus: 连接已关闭

(electron-ssr:14692): LIBDBUSMENU-GLIB-WARNING **: 15:46:24.936: Unable to get session bus: 连接已关闭
2020-02-13 15:46:26:200 [info] IPv6 support

2020-02-13 15:46:26:202 [error] Traceback (most recent call last):
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 303, in get_config
    check_config(config, is_local)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 132, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 91, in __init__
    random_string(self._method_info[1]))
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 120, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 94, in __init__
    load_libsodium()
  File "/root/.config/electron-ssr/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 44, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

2020-02-13 15:46:27:351 [error] Unhandled Rejection at: Promise [object Promise], reason: Error: net::ERR_CONNECTION_REFUSED

**Comment by xVanTuring** [comment]
Then you should install libsodium with your package manager tool

**Comment by iefhong** [comment]
切换账号，打开程序重新安装后正常
